data:
  image_size: 32
  data_root: '/home/minzhe_guo/Downloads/cifar-10-batches-py'
  output_size: 32
  dataset: CIFAR10
eval:
  begin_ckpt: 20
  end_ckpt: 20
  num_samples: 50000
  eval_folder: outputs/txt2img-samples/epoch=000030
  batch_size: 500
work_dir: '/home/minzhe_guo/Documents/GitHub/stable2'
